[project]
name = "csa-lab4"
version = "0.1.0"
description = "Forth -> accumulator processor: translator + tick-accurate simulator"
requires-python = ">=3.10"

[tool.ruff]
line-length = 120
target-version = "py310"
extend-exclude = ["venv", ".venv", "__pycache__", "tests"]

[tool.ruff.lint]
select = [
  "E", "F", "W",   # pycodestyle / pyflakes
  "I",             # isort
  "UP",            # pyupgrade
  "B",             # bugbear
  "SIM",           # simplify
  "RUF",           # ruff specific
]

ignore = [
	"RUF001", # ambiguous unicode in strings
	"RUF002", # ambiguous unicode in docstrings
	"RUF003", # ambiguous unicode in comments
]

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
strict_equality = true
exclude = "^(tests/|venv/|\\.venv/|__pycache__/)"

[tool.pytest.ini_options]
testpaths = ["golden"]
python_files = ["test_*.py"]
addopts = "-ra --tb=short"
